# This is a basic workflow to help you get started with Actions

name: Update data.json

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "0 0 * * *" #Run every midnight

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: |
        python -m pip install --upgrade pip
        pip install requests
    - run: python update_data.py
    # Git add, commit and push the data/*.json files to the current branch
    - uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
      with:
        add: '.'
        message: 'Nightly update of data/*.json from GitHub Actions'

      env:
        # This is necessary in order to push a commit to the repo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
